title: delicate

# Header
menu:
  主页: /
  档案: /archives
  关于: /about

# Read More text
excerpt_link: 阅读更多

# siderbar infomation
## sidebar-about
siderbar:
  name: 陈科衡
  logo: Time wait for no one.
  tag: 
    - 学生
    - 前端开发者
    - hexo开发者
    - 海洋测绘专业
    - 上海海洋大学
    - delicate主题开发者
  social: 
    bilibili: https://space.bilibili.com/481922596
    github: https://github.com/can-dy-jack
    twitter: https://twitter.com/kartjim
    CSDN: https://blog.csdn.net/qq_46590483?spm=1000.2115.3001.5343
    codepen: https://codepen.io/Kartjim

